name: pcmc_staff
description: PCMC Staff

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  quickalert: ^1.0.1

  http: 0.13.4
  


  shared_preferences: ^2.1.1

  camera: ^0.10.5+2



  path: ^1.8.3





  webview_flutter: ^2.0.4

  convert: ^3.1.1



  cupertino_icons: ^1.0.2

  carousel_slider: ^4.2.1

  permission_handler: ^10.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  local_auth: ^2.1.6
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/


