name: pcmc_staff
description: PCMC Staff

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  quickalert: ^1.0.1

  http: 0.13.4
  
  permission_handler: ^9.2.0

  shared_preferences: ^2.1.1

  camera: ^0.10.5+2

  path_provider: ^2.0.15

  path: ^1.8.3

  image_picker: ^0.8.7+5

  geolocator: ^9.0.2

  webview_flutter: ^2.0.4

  convert: ^3.1.1

  flutter_image_compress: ^2.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


